
INSERT INTO PERSONS (DNI,NAME,SURNAME, PARTY_ID) VALUES('39667501',	'Federico',	'Figueroa', NULL);
INSERT INTO PERSONS (DNI,NAME,SURNAME, PARTY_ID) VALUES('39667502',	'Gabriela',	'Chavez', NULL);
INSERT INTO PERSONS (DNI,NAME,SURNAME, PARTY_ID) VALUES('39667506',	'guns',	'roses', NULL);
INSERT INTO PERSONS (DNI,NAME,SURNAME, PARTY_ID) VALUES('39667507',	'rolling',	'stones', NULL);
INSERT INTO PERSONS (DNI,NAME,SURNAME, PARTY_ID) VALUES('39667508',	'metallica',	'metallica', NULL);
INSERT INTO PERSONS (DNI,NAME,SURNAME, PARTY_ID) VALUES('39667509',	'pantera',	'pantera', NULL);