
INSERT INTO PERSONS (DNI,NAME,SURNAME) VALUES('39667501',	'Federico',	'Figueroa');
INSERT INTO PERSONS (DNI,NAME,SURNAME) VALUES('39667502',	'Gabriela',	'Chavez');
INSERT INTO PERSONS (DNI,NAME,SURNAME) VALUES('39667503',	'algo',	'algo');
INSERT INTO PERSONS (DNI,NAME,SURNAME) VALUES('39667504',	'quiien',	'quien');
INSERT INTO PERSONS (DNI,NAME,SURNAME) VALUES('39667505',	'callejeros',	'callejeros');
INSERT INTO PERSONS (DNI,NAME,SURNAME) VALUES('39667506',	'guns',	'roses');
INSERT INTO PERSONS (DNI,NAME,SURNAME) VALUES('39667507',	'rolling',	'stones');
INSERT INTO PERSONS (DNI,NAME,SURNAME) VALUES('39667508',	'metallica',	'metallica');
INSERT INTO PERSONS (DNI,NAME,SURNAME) VALUES('39667509',	'pantera',	'pantera');